on:
  pull_request:
  push:
    branches-ignore:
      - 'dev'
jobs:
  test-build:
    runs-on: docker
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    steps:
      - name: Clone repository
        run: git clone ${{ github.event.repository.clone_url }} --branch=${{ github.ref_name }} --depth=1 /iceshrimp
      - name: Build backend & frontend
        run: |
          cd /iceshrimp/Iceshrimp.Backend
          dotnet restore
          dotnet build
      - name: Run tests
        run: |
          cd /iceshrimp
          dotnet test
