on:
  pull_request:
  push:
    branches-ignore:
      - 'dev'
jobs:
  test-build:
    runs-on: docker
    container:
      image: iceshrimp.dev/iceshrimp/dotnet-sdk:8.0-alpine
      options: --volume /opt/iceshrimp-cache/nuget:/root/.nuget
    steps:
      - name: Clone repository
        run: git clone ${{ github.event.repository.clone_url }} --branch=${{ github.ref_name }} --depth=1 /iceshrimp
      - name: Run tests
        run: |
          cd /iceshrimp
          dotnet test
