on:
  pull_request:
  push:
    branches-ignore:
      - 'dev'
jobs:
  test-build:
    runs-on: docker
    container:
      image: iceshrimp.dev/iceshrimp/dotnet-sdk:8.0-alpine
      options: --volume /opt/iceshrimp-cache/nuget:/root/.nuget
    steps:
      - name: Clone repository
        shell: bash
        run: |
          mkdir /iceshrimp
          cd /iceshrimp
          git init
          git remote add origin ${{ github.event.repository.clone_url }}
          git fetch origin ${{ github.ref }} --depth=1
          git checkout --detach FETCH_HEAD
      - name: Run tests
        run: |
          cd /iceshrimp
          dotnet test
