//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iceshrimp.Frontend.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Iceshrimp.Frontend.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Timestamp_Day_X {
            get {
                return ResourceManager.GetString("Timestamp_Day_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Hour_X {
            get {
                return ResourceManager.GetString("Timestamp_Hour_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Minute_X {
            get {
                return ResourceManager.GetString("Timestamp_Minute_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Month_X {
            get {
                return ResourceManager.GetString("Timestamp_Month_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Week_X {
            get {
                return ResourceManager.GetString("Timestamp_Week_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Year_X {
            get {
                return ResourceManager.GetString("Timestamp_Year_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_JustNow {
            get {
                return ResourceManager.GetString("Timestamp_JustNow", resourceCulture);
            }
        }
        
        internal static string Timestamp_Second_X {
            get {
                return ResourceManager.GetString("Timestamp_Second_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Now {
            get {
                return ResourceManager.GetString("Timestamp_Now", resourceCulture);
            }
        }
        
        internal static string Common_Timeline {
            get {
                return ResourceManager.GetString("Common_Timeline", resourceCulture);
            }
        }
        
        internal static string Common_Notifications {
            get {
                return ResourceManager.GetString("Common_Notifications", resourceCulture);
            }
        }
        
        internal static string Common_Note {
            get {
                return ResourceManager.GetString("Common_Note", resourceCulture);
            }
        }
        
        internal static string Compose_PublishNote {
            get {
                return ResourceManager.GetString("Compose_PublishNote", resourceCulture);
            }
        }
        
        internal static string Compose_SaveEdit {
            get {
                return ResourceManager.GetString("Compose_SaveEdit", resourceCulture);
            }
        }
        
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
    }
}
