//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iceshrimp.Frontend.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Iceshrimp.Frontend.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Timestamp_Day_X {
            get {
                return ResourceManager.GetString("Timestamp_Day_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Hour_X {
            get {
                return ResourceManager.GetString("Timestamp_Hour_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Minute_X {
            get {
                return ResourceManager.GetString("Timestamp_Minute_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Month_X {
            get {
                return ResourceManager.GetString("Timestamp_Month_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Week_X {
            get {
                return ResourceManager.GetString("Timestamp_Week_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Year_X {
            get {
                return ResourceManager.GetString("Timestamp_Year_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_JustNow {
            get {
                return ResourceManager.GetString("Timestamp_JustNow", resourceCulture);
            }
        }
        
        internal static string Timestamp_Second_X {
            get {
                return ResourceManager.GetString("Timestamp_Second_X", resourceCulture);
            }
        }
        
        internal static string Timestamp_Now {
            get {
                return ResourceManager.GetString("Timestamp_Now", resourceCulture);
            }
        }
        
        internal static string Common_Timeline {
            get {
                return ResourceManager.GetString("Common_Timeline", resourceCulture);
            }
        }
        
        internal static string Common_Notifications {
            get {
                return ResourceManager.GetString("Common_Notifications", resourceCulture);
            }
        }
        
        internal static string Common_Note {
            get {
                return ResourceManager.GetString("Common_Note", resourceCulture);
            }
        }
        
        internal static string Compose_PublishNote {
            get {
                return ResourceManager.GetString("Compose_PublishNote", resourceCulture);
            }
        }
        
        internal static string Compose_SaveEdit {
            get {
                return ResourceManager.GetString("Compose_SaveEdit", resourceCulture);
            }
        }
        
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        internal static string Preferences_UILanguage {
            get {
                return ResourceManager.GetString("Preferences_UILanguage", resourceCulture);
            }
        }
        
        internal static string StateButton_SaveChanges {
            get {
                return ResourceManager.GetString("StateButton_SaveChanges", resourceCulture);
            }
        }
        
        internal static string Preferences_FollowBrowserPref {
            get {
                return ResourceManager.GetString("Preferences_FollowBrowserPref", resourceCulture);
            }
        }
        
        internal static string Preferences_Appearance {
            get {
                return ResourceManager.GetString("Preferences_Appearance", resourceCulture);
            }
        }
        
        internal static string StateButton_Saved {
            get {
                return ResourceManager.GetString("StateButton_Saved", resourceCulture);
            }
        }
        
        internal static string StateButton_Loading {
            get {
                return ResourceManager.GetString("StateButton_Loading", resourceCulture);
            }
        }
        
        internal static string StateButton_Error {
            get {
                return ResourceManager.GetString("StateButton_Error", resourceCulture);
            }
        }
        
        internal static string Preferences_Theme {
            get {
                return ResourceManager.GetString("Preferences_Theme", resourceCulture);
            }
        }
        
        internal static string Preferences_CustomCSS {
            get {
                return ResourceManager.GetString("Preferences_CustomCSS", resourceCulture);
            }
        }
        
        internal static string Preferences_ThemeLight {
            get {
                return ResourceManager.GetString("Preferences_ThemeLight", resourceCulture);
            }
        }
        
        internal static string Preferences_ThemeDark {
            get {
                return ResourceManager.GetString("Preferences_ThemeDark", resourceCulture);
            }
        }
        
        internal static string Preferences_ThemeSystem {
            get {
                return ResourceManager.GetString("Preferences_ThemeSystem", resourceCulture);
            }
        }
        
        internal static string Preferences_CustomCSS_Warning {
            get {
                return ResourceManager.GetString("Preferences_CustomCSS_Warning", resourceCulture);
            }
        }
        
        internal static string Error_Api_Unknown {
            get {
                return ResourceManager.GetString("Error_Api_Unknown", resourceCulture);
            }
        }
        
        internal static string Error_Api_Timeout {
            get {
                return ResourceManager.GetString("Error_Api_Timeout", resourceCulture);
            }
        }
        
        internal static string Error_Api_Json_Message {
            get {
                return ResourceManager.GetString("Error_Api_Json_Message", resourceCulture);
            }
        }
        
        internal static string Error_Api_Json_Path_Message {
            get {
                return ResourceManager.GetString("Error_Api_Json_Path_Message", resourceCulture);
            }
        }
        
        internal static string Error_Api_Http_Request {
            get {
                return ResourceManager.GetString("Error_Api_Http_Request", resourceCulture);
            }
        }
        
        internal static string Error_Api_Http_Status {
            get {
                return ResourceManager.GetString("Error_Api_Http_Status", resourceCulture);
            }
        }
        
        internal static string Note_RenotedLabel {
            get {
                return ResourceManager.GetString("Note_RenotedLabel", resourceCulture);
            }
        }
        
        internal static string Note_HiddenByFilter {
            get {
                return ResourceManager.GetString("Note_HiddenByFilter", resourceCulture);
            }
        }
        
        internal static string Common_Show {
            get {
                return ResourceManager.GetString("Common_Show", resourceCulture);
            }
        }
        
        internal static string Common_Hide {
            get {
                return ResourceManager.GetString("Common_Hide", resourceCulture);
            }
        }
        
        internal static string Note_CwShow {
            get {
                return ResourceManager.GetString("Note_CwShow", resourceCulture);
            }
        }
        
        internal static string Note_CwHide {
            get {
                return ResourceManager.GetString("Note_CwHide", resourceCulture);
            }
        }
        
        internal static string Note_CwShow_Characters {
            get {
                return ResourceManager.GetString("Note_CwShow_Characters", resourceCulture);
            }
        }
        
        internal static string Note_Renote {
            get {
                return ResourceManager.GetString("Note_Renote", resourceCulture);
            }
        }
        
        internal static string Note_Renote_Unlisted {
            get {
                return ResourceManager.GetString("Note_Renote_Unlisted", resourceCulture);
            }
        }
        
        internal static string Note_Renote_Followers {
            get {
                return ResourceManager.GetString("Note_Renote_Followers", resourceCulture);
            }
        }
        
        internal static string Note_Unrenote {
            get {
                return ResourceManager.GetString("Note_Unrenote", resourceCulture);
            }
        }
        
        internal static string Common_Refetch {
            get {
                return ResourceManager.GetString("Common_Refetch", resourceCulture);
            }
        }
        
        internal static string Note_Menu_Bookmark_Add {
            get {
                return ResourceManager.GetString("Note_Menu_Bookmark_Add", resourceCulture);
            }
        }
        
        internal static string Note_Menu_Bookmark_Remove {
            get {
                return ResourceManager.GetString("Note_Menu_Bookmark_Remove", resourceCulture);
            }
        }
        
        internal static string Note_Menu_Pin {
            get {
                return ResourceManager.GetString("Note_Menu_Pin", resourceCulture);
            }
        }
        
        internal static string Note_Menu_Unpin {
            get {
                return ResourceManager.GetString("Note_Menu_Unpin", resourceCulture);
            }
        }
        
        internal static string Note_Menu_MuteThread {
            get {
                return ResourceManager.GetString("Note_Menu_MuteThread", resourceCulture);
            }
        }
        
        internal static string Common_AboutPage {
            get {
                return ResourceManager.GetString("Common_AboutPage", resourceCulture);
            }
        }
        
        internal static string Common_OpenOriginal {
            get {
                return ResourceManager.GetString("Common_OpenOriginal", resourceCulture);
            }
        }
        
        internal static string Common_Bite {
            get {
                return ResourceManager.GetString("Common_Bite", resourceCulture);
            }
        }
        
        internal static string Common_Share {
            get {
                return ResourceManager.GetString("Common_Share", resourceCulture);
            }
        }
        
        internal static string Common_CopyLink {
            get {
                return ResourceManager.GetString("Common_CopyLink", resourceCulture);
            }
        }
        
        internal static string Common_CopyLink_Remote {
            get {
                return ResourceManager.GetString("Common_CopyLink_Remote", resourceCulture);
            }
        }
        
        internal static string Note_Menu_CopyContents {
            get {
                return ResourceManager.GetString("Note_Menu_CopyContents", resourceCulture);
            }
        }
        
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        internal static string Note_Menu_Redraft {
            get {
                return ResourceManager.GetString("Note_Menu_Redraft", resourceCulture);
            }
        }
        
        internal static string Note_Menu_Report {
            get {
                return ResourceManager.GetString("Note_Menu_Report", resourceCulture);
            }
        }
        
        internal static string Note_Visibility_Public {
            get {
                return ResourceManager.GetString("Note_Visibility_Public", resourceCulture);
            }
        }
        
        internal static string Note_Visibility_Unlisted {
            get {
                return ResourceManager.GetString("Note_Visibility_Unlisted", resourceCulture);
            }
        }
        
        internal static string Note_Visibility_Followers {
            get {
                return ResourceManager.GetString("Note_Visibility_Followers", resourceCulture);
            }
        }
        
        internal static string Note_Visibility_Specified {
            get {
                return ResourceManager.GetString("Note_Visibility_Specified", resourceCulture);
            }
        }
        
        internal static string Note_Poll_Vote {
            get {
                return ResourceManager.GetString("Note_Poll_Vote", resourceCulture);
            }
        }
        
        internal static string Note_Poll_VoteCount_Choice {
            get {
                return ResourceManager.GetString("Note_Poll_VoteCount_Choice", resourceCulture);
            }
        }
        
        internal static string Note_Poll_MultipleChoice {
            get {
                return ResourceManager.GetString("Note_Poll_MultipleChoice", resourceCulture);
            }
        }
        
        internal static string Note_Poll_VoteCount_Total {
            get {
                return ResourceManager.GetString("Note_Poll_VoteCount_Total", resourceCulture);
            }
        }
        
        internal static string Note_Poll_Expired {
            get {
                return ResourceManager.GetString("Note_Poll_Expired", resourceCulture);
            }
        }
        
        internal static string Note_Poll_ExpiresAt_DateTime {
            get {
                return ResourceManager.GetString("Note_Poll_ExpiresAt_DateTime", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Sensitive {
            get {
                return ResourceManager.GetString("Drive_Entry_Sensitive", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_NoAlt {
            get {
                return ResourceManager.GetString("Drive_Entry_NoAlt", resourceCulture);
            }
        }
        
        internal static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        internal static string Drive_Status {
            get {
                return ResourceManager.GetString("Drive_Status", resourceCulture);
            }
        }
        
        internal static string Drive_Folder_Create {
            get {
                return ResourceManager.GetString("Drive_Folder_Create", resourceCulture);
            }
        }
        
        internal static string Drive_Folder_Delete {
            get {
                return ResourceManager.GetString("Drive_Folder_Delete", resourceCulture);
            }
        }
        
        internal static string Drive_UploadFile {
            get {
                return ResourceManager.GetString("Drive_UploadFile", resourceCulture);
            }
        }
        
        internal static string Drive_Count_Folders_Files {
            get {
                return ResourceManager.GetString("Drive_Count_Folders_Files", resourceCulture);
            }
        }
        
        internal static string Drive_Status_FileCount {
            get {
                return ResourceManager.GetString("Drive_Status_FileCount", resourceCulture);
            }
        }
        
        internal static string Drive_Status_Usage_Size {
            get {
                return ResourceManager.GetString("Drive_Status_Usage_Size", resourceCulture);
            }
        }
        
        internal static string Drive_CreateFolderDialog_Placeholder {
            get {
                return ResourceManager.GetString("Drive_CreateFolderDialog_Placeholder", resourceCulture);
            }
        }
        
        internal static string Drive_CreateFolderDialog_Confirm {
            get {
                return ResourceManager.GetString("Drive_CreateFolderDialog_Confirm", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Avatar {
            get {
                return ResourceManager.GetString("Drive_Entry_Avatar", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Banner {
            get {
                return ResourceManager.GetString("Drive_Entry_Banner", resourceCulture);
            }
        }
        
        internal static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Menu_Move {
            get {
                return ResourceManager.GetString("Drive_Entry_Menu_Move", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Menu_SetAlt {
            get {
                return ResourceManager.GetString("Drive_Entry_Menu_SetAlt", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Menu_Sensitive_Add {
            get {
                return ResourceManager.GetString("Drive_Entry_Menu_Sensitive_Add", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_Menu_Sensitive_Remove {
            get {
                return ResourceManager.GetString("Drive_Entry_Menu_Sensitive_Remove", resourceCulture);
            }
        }
        
        internal static string Common_Rename {
            get {
                return ResourceManager.GetString("Common_Rename", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_RenameDialog_FilePlaceholder {
            get {
                return ResourceManager.GetString("Drive_Entry_RenameDialog_FilePlaceholder", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_RenameDialog_FolderPlaceholder {
            get {
                return ResourceManager.GetString("Drive_Entry_RenameDialog_FolderPlaceholder", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_RenameDialog_Confirm {
            get {
                return ResourceManager.GetString("Drive_Entry_RenameDialog_Confirm", resourceCulture);
            }
        }
        
        internal static string Drive_Entry_DeleteDialog_Question {
            get {
                return ResourceManager.GetString("Drive_Entry_DeleteDialog_Question", resourceCulture);
            }
        }
    }
}
