name: .Net and Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'
  push:
    branches: [ "dev" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add ice repository
        run: |
          git remote add ice https://iceshrimp.dev/iceshrimp/Iceshrimp.NET.git
          git fetch ice

      - name: Sync ice branch to upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions" 
          git config --global user.email "actions@github.com"
          git checkout upstream || git checkout -b upstream
          UPSTREAM_BRANCH="${{ inputs.upstream_branch || 'dev' }}"
          git merge ice/$UPSTREAM_BRANCH --allow-unrelated-histories

      - name: Push updates to origin/upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin upstream -f
      
  build:
    runs-on: ubuntu-latest
    
    needs: sync
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout repository (sync branch)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: upstream
          
      # Step 2: Fetch previous build commit hash (if exists)
      - name: Fetch previous commit hash
        id: get-previous-hash
        run: |
          echo "PREVIOUS_HASH=$(cat .previous_commit_hash || echo '')" >> $GITHUB_ENV
        continue-on-error: true

      # Step 3: Check if there are updates in the branch
      - name: Check for branch updates
        id: check-updates
        run: |
          CURRENT_HASH=$(git rev-parse HEAD)
          if [ "$CURRENT_HASH" = "$PREVIOUS_HASH" ]; then
            echo "No changes detected. Skipping build."
            echo "SHOULD_BUILD=false" >> $GITHUB_ENV
          else
            echo "Changes detected. Proceeding with build."
            echo "SHOULD_BUILD=true" >> $GITHUB_ENV

      # Step 4: Save the current commit hash for future runs
      - name: Save current commit hash
        if: ${{ github.event_name != 'pull_request' && env.SHOULD_BUILD == 'true' }}
        run: |
          echo $(git rev-parse HEAD) > .previous_commit_hash
          git add .previous_commit_hash
          git commit -m "Save commit hash for future runs"
          git push origin upstream

      # Install cosign tool except on PR
      - name: Install cosign
        if: ${{ github.event_name != 'pull_request' && env.SHOULD_BUILD == 'true' }}
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        
      # Log into registry
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.event_name != 'pull_request' && env.SHOULD_BUILD == 'true' }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker
      - name: Extract Docker metadata
        id: meta
        if: ${{ github.event_name != 'pull_request' && env.SHOULD_BUILD == 'true' }}
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        if: ${{ github.event_name != 'pull_request' && env.SHOULD_BUILD == 'true' }}
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          build-args: AOT=true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the Docker image (skip on PR)
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && env.SHOULD_BUILD == 'true' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
